import type { Metadata } from "next";
import { Tektur, Tac_One } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";
import Footer from "@/components/Footer";

const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
});

const tacOne = Tac_One({
  variable: "--font-tac-one",
  subsets: ["latin"],
  weight : ['400'],
  display : 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${tektur.variable} ${tacOne.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
